# Generated by Django 3.0.6 on 2020-05-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0002_auto_20200515_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('after_shave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.AfterShave')),
                ('blades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Blade')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Color')),
                ('gift_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.GiftSet')),
                ('razor_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.RazorSet')),
                ('shaving_gel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ShavingGel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
